### ISSUE TITLE
[BUG] Photo ID After Face is already enrolled is stuck

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#12]
**Describe the bug**
I enrolled my face. 
Then, I clicked on the Photo ID button and hit the Predict button.

**Screenshots**
See video here:  https://youtu.be/s6ZMdcDHFpI

**Desktop (please complete the following information):**
Win10 Laptop using Chrome

**Additional context**
You will see in the video that the software reports the face on the Photo ID card does not match my enroll image.

**Comment by loainagati** [comment]
Fixed. Please take a look
