### ISSUE TITLE
For Okta - Add Metadata and Cert download to Wiki

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#13]
Hi Srie, can you please add "step by step" instructions on how to build the IdP and the metadata and cert download for Billy.  Thanks. 

Please provide a link to the documentation entry
https://github.com/openinfer/PrivateIdentity/wiki/External-Integration

Please share Screenshots if you can.

**Comment by sriesow** [comment]
Edited the wiki to point the certificate link and updated the screenshot and instructions
