### ISSUE TITLE
[Feature request] Enroll User If Okta SAML request contains new email addr  

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#15]
This is a temporary work-around.  
Okta does not alert us to incoming Enroll request (the SAML request looks the same as verify).
If we see a new email address we have not seen before, use that fact to trigger the enroll.
This will be depreciated as soon as Okta fixes their bug.
Thanks.

**System information**
PrivateID SAML endpoint

**Comment by sriesow** [comment]
Completed and Pushed to Devel branch. Open for Testing
