### ISSUE TITLE
Add to PING Identity implementation docs 

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#20]
Please add document the PING setup for:  
 - Enroll  
 - Verified Enroll 
 - Login with Face, 
 - Login with Face+Voice 
 - Recover Password
 - Forget User
 - Delete User 
(These are the buttons here:  https://ping.private.id/ping.html ) 
Please provide a link to the documentation entry
https://github.com/openinfer/PrivateIdentity/wiki/External-Integration#ping-identity

**Comment by sriesow** [comment]
I have added the above-described modalities in the ping identity section. Please take a look at it and let me know if any changes are required.

[Sample Ping Demo](https://github.com/openinfer/PrivateIdentity/wiki/External-Integration#sample-ping-demo)
