### ISSUE TITLE
Documentation for Customer Integrations 

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#22]
Create a new page on Wiki to describes all options available for customer integrations. 
**"Customer Integrations"**

**DIV/HTML**

- Built in React (pluggable) 
- Embed as a DIV

**PaaS (Web Tier)**

- Docker Image
- Runs elastic, load balanced, fault tolerant K8s
- Connects to a Server Side Component managed by Private Identity
- Runs on any cloud (AWS, GCP, Azure) 

**PaaS (Entire Tier)**

- Docker Images
- Runs elastic, load balanced, fault tolerant K8s
- Includes Server Side Component managed by RSA
- Runs on any cloud (AWS, GCP, Azure) 

**SaaS (Open)**

- Entirely managed and run on AWS by Private Identity 
- API Key access
- Fully elastic, load balanced, fault tolerant

**SaaS (Dedicated for Customer)**

- Entire K8s cluster dedicated to Customer
- Entirely managed and run on AWS by Private Identity 
- API Key access
- Fully elastic, load balanced, fault tolerant

**RESTful API**

- Receives fully homomorphic encryption (FHE) payload from client device 
- Returns UUIDs 
- Runs all ciphertext and plaintext business methods  

**Encryption Engine** 

- Cluster for biometric ingestion
- Elastic, load balanced, fault tolerant K8s, autoscale to 1000s of nodes
- Javascript API and RESTful API 

**W3C/FIDO2 WebAuthn (polymorphic interface)** 

- Authenticator enrolment 
- Authenticator authentication 

**Photo ID Verification**

- DIV/HTML 
- Javascript API
- Server Side RESTful API

**Comment by OpenInference** [comment]
Completed with Hrefs.
