### ISSUE TITLE
[BUG] Re-Add Spoof Icon during video spoof detection

### ISSUE THREAD

**Issue by holiday-kody** [openinfer/PrivateIdentity#34]
The video spoof detection icon no longer appears when a spoof video is detected. The dimness/brightness detection disabled the icon from appearing. 

Before:

[https://github.com/openinfer/PrivateIdentity/blob/master/images/video_spoof_demo.png](url)

**Comment by nikita-lazarev-up** [comment]
Hello, @holiday-kody.
I talked to @loainagati and he told me what we had canceled the dimness/brightness detection.
Currently, when the video spoof is detected the icon appears. Could you check and confirm this, please?

![image](https://user-images.githubusercontent.com/59693179/86105796-73f6c880-bac8-11ea-8a5b-7c50eb871edf.png)
