### ISSUE TITLE
[BUG]Ping Demo page - Forget User button href has an old API key

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#47]
Please update the API key on ping.private.id/ping.html "Forget User" button's href.   

Thanks,

**Comment by sriesow** [comment]
Hi Mike,

Working on it. We need to get into the Ping RDP to change the link. Currently, the system is locked for 24 hours as we used the wrong password. Will try to reset / login and will let you know once the link is changed.

Thanks,
Srie Raam

**Comment by sriesow** [comment]
Hi Mike,

Was able to log in to RDP and the bug has been fixed.

Thanks,
Srie Raam
