### ISSUE TITLE
[BUG] Incorrect error message on iOS w/ Gmail client when I select Chrome instead of Safari

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#51]
**Describe the bug**
This is an error condition, but the error message is incorrect.  The user is only allowed to use the Safari browser in the iOS environment.  

**Screenshots**
![IMG_0136](https://user-images.githubusercontent.com/46856299/91123232-5bd79b80-e66a-11ea-893f-f6fb57f2d255.PNG)

I clicked on the private.id/demo URL from within the Gmail client on an iOS device and then selected to launch the app in Chrome (it gives me the choice between Chrome & Safari). 

The correct error message displays if I paste the URL directly into the Chrome browser without using the iOS gmail client.

**Comment by OpenInference** [comment]
Fixed by Anas on October 7, 2020.
