### ISSUE TITLE
Vertical ID Support in Document Verification

### ISSUE THREAD

**Issue by holiday-kody** [openinfer/PrivateIdentity#7]
The Document verification currently covers Horizontal Identification Cards, however there are cases of Vertical Licences, for example a drivers license for someone that is under the age of 21 in the United States will have a vertical license.

**Comment by PrivateBio** [comment]
![vertical license](https://user-images.githubusercontent.com/46856299/84859111-75d97a00-b03a-11ea-8aa1-f65179bb2122.jpg)
